# Generated by Django 4.0.2 on 2022-04-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentfirstname', models.CharField(max_length=60)),
                ('studentlastname', models.CharField(max_length=60)),
                ('branch', models.CharField(max_length=60)),
                ('enrollnumber', models.IntegerField()),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
    ]
