# Generated by Django 4.0.2 on 2022-04-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordio', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Issuedate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
