# Generated by Django 4.0.2 on 2022-04-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordio', '0003_book_issuedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='issuedbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentfirstname', models.CharField(max_length=60)),
                ('enrollnumber', models.IntegerField()),
                ('branch', models.CharField(max_length=60)),
                ('Issuedate', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='Issuedate',
        ),
    ]
