# Generated by Django 4.0.2 on 2022-04-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordio', '0004_issuedbook_remove_book_issuedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='issuedbooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=60)),
                ('enrollnumber', models.IntegerField()),
                ('branch', models.CharField(max_length=60)),
                ('bookname', models.CharField(max_length=60)),
                ('auther', models.CharField(max_length=60)),
                ('issueddate', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='issuedbook',
        ),
    ]
