# Generated by Django 4.0.2 on 2022-04-06 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywordio', '0005_issuedbooks_delete_issuedbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedbooks',
            name='auther',
        ),
        migrations.RemoveField(
            model_name='issuedbooks',
            name='enrollnumber',
        ),
    ]
