# Generated by Django 4.0.2 on 2022-04-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordio', '0006_remove_issuedbooks_auther_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedbooks',
            name='expiryddate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='issuedbooks',
            name='studentenrollnumber',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollnumber',
            field=models.IntegerField(default=1),
        ),
    ]
