# Generated by Django 4.0.2 on 2022-04-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordio', '0007_issuedbooks_expiryddate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuedbooks',
            old_name='studentenrollnumber',
            new_name='enrollnumber',
        ),
        migrations.AddField(
            model_name='issuedbooks',
            name='auther',
            field=models.CharField(default='0000000', max_length=60),
        ),
    ]
