# Generated by Django 4.0.2 on 2022-04-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordio', '0008_rename_studentenrollnumber_issuedbooks_enrollnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentissue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdinfo', models.CharField(max_length=60)),
                ('book', models.CharField(max_length=60)),
                ('issue_date', models.DateField(auto_now_add=True, null=True)),
                ('expiry_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
