# Generated by Django 4.0.2 on 2022-04-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordio', '0009_studentissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentissue',
            name='book',
            field=models.CharField(default='0000000', max_length=60),
        ),
        migrations.AlterField(
            model_name='studentissue',
            name='stdinfo',
            field=models.CharField(default='0000000', max_length=60),
        ),
    ]
