# Generated by Django 4.0.2 on 2022-04-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordio', '0010_alter_studentissue_book_alter_studentissue_stdinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbooks',
            name='auther',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='issuedbooks',
            name='enrollnumber',
            field=models.IntegerField(default=''),
        ),
    ]
