# Generated by Django 4.0.2 on 2022-04-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordio', '0011_alter_issuedbooks_auther_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbooks',
            name='auther',
            field=models.CharField(default='N/A', max_length=60),
        ),
    ]
