# Generated by Django 4.0.2 on 2022-04-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordio', '0012_alter_issuedbooks_auther'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbooks',
            name='expiryddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
